### ISSUE TITLE
[BUG]: Indentation Error in ToC

### ISSUE THREAD

**Issue by Mandy-cyber** [Mandy-cyber/Markdown-ToC-Generator#1]
### Context
Currently, if you run `mdtoc` on this repository's `README.md` the generated Table of Contents looks as follows:

![image](https://github.com/user-attachments/assets/087823c3-17d5-4223-8189-25695dc80dba)

As you can see, the first few headers are all indented one off the level they should be.

### Acceptance Criteria
- Fork this repository and make a new branch
- Find and fix the cause of the bug
- Create a PR with evidence of the fix

<br>

Happy coding! ❤️ 
-Mandy

**Comment by A1r0x** [comment]
This might be an issue with the way the README.md file is formatted. I don't know if this was your intention, but Installation Guide, Usage Instructions, and Example are all being treated as the same heading level in the table of contents, but in the actual markdown, Installation Guide is a Header 2 while the rest are Header 1

**Comment by Mandy-cyber** [comment]
So the thing is, I want it to be able to work even if the order of levels is weird. This is because a lot of the times i choose heading levels not based on the order they should be in but simply what size I want stuff haha. I still want them to be nested in a way that looks correct. Think I got a  fix out though.

**Comment by Mandy-cyber** [comment]
Accidentally marked this one as hacktoberfest (my bad!). Will be putting up more hacktoberfest issues soon!
