### ISSUE TITLE
[DOCS]: Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Mandy-cyber** [Mandy-cyber/Markdown-ToC-Generator#14]
### Context
The `CONTRIBUTING.md` file is ugly, too formal, and probably missing some information xD. Let's fix that! Check out some other `CONTRIBUTING.md` files for inspiration or get creative!

### Acceptance Criteria
- Fork this repository and make a new branch
- Update the `CONTRIBUTING.md` (content-wise and aesthetic-wise!)
- Create a PR

<br>

Happy coding! ❤️ 
-Mandy

**Comment by DeathwingIN** [comment]
can u assign me to this
