### ISSUE TITLE
[DOCS]: Update README.md 

### ISSUE THREAD

**Issue by Mandy-cyber** [Mandy-cyber/Markdown-ToC-Generator#2]
### Context
The `README.md` file is out of date, ugly, and probably missing import information xD. Let's fix that! Check out some of my other repos for my typical style of `README` or get creative!

### Acceptance Criteria
- Fork this repository and make a new branch
- Update the `README.md` (content wise and aesthetic wise!)
- Create a PR

<br>

Happy coding! ❤️ 
-Mandy

**Comment by danieltayal07** [comment]
hey i would like to contribute
please assign me this!

**Comment by Kushagra614** [comment]
Hey, I would really love to contribute to your Project and make an amamzing README file, Please Assign me this issue. @Mandy-cyber

**Comment by danieltayal07** [comment]
hey @Mandy-cyber hope you are good,
I commented first and i started the work and also i have now requested a pull

please consider mine if possible!

Thanks

**Comment by Mandy-cyber** [comment]
Hi! It says that Kushagra commented on it first. 

> hey @Mandy-cyber hope you are good, I commented on the issue first and i started the work and also i have now requested a pull
> 
> please consider mine if possible!
> 
> Thanks

**Comment by Mandy-cyber** [comment]
> hey @Mandy-cyber hope you are good, I commented on the issue first and i started the work and also i have now requested a pull
> 
> please consider mine if possible!
> 
> Thanks

Apologies, i got confused since he edited his message lol

**Comment by danieltayal07** [comment]
Thank you! @Mandy-cyber for considering
